### ISSUE TITLE
Uberspace ist voll

### ISSUE THREAD

**Issue by Moercell** [v1bes/achahha#1]
ich hab mir die zip mal angeguckt und ich glaube du hattest eh etwas zu viel geladen 
(sollten nur ca. 1.2 gb sein)
also wenn wir vielleicht die backups löschen und ein bisschen aufräumen sollte das wieder gehen.
vielleicht mach wir mal eine liste mit den seiten die drauf bleiben müssen (auch wegen uni stuff).

**Comment by elhenro** [comment]
jo, habe ich beides so gemacht.. :)
gute idee mit der list.. vllt schreibe ich mal ein skript das alle seiten in einem csv auflistet mit größe und traffic oder so
