### ISSUE TITLE
Detailseite Layout Problem

### ISSUE THREAD

**Issue by elhenro** [v1bes/achahha#4]
Bilder der Produkte werden auf der Detailseite nicht nacheinander angezeigt. Letztes rutscht nach unten  ( https://achahha.de/produkt/v-neck-strick-pullover-schwarz/).

**Comment by marcolilli** [comment]
Fixed durch custom CSS.
```
.woocommerce div.product .woocommerce-product-gallery--columns-5 .flex-control-thumbs li:nth-child(5n+1) {
    clear: none;
}
```
Ist anscheinend ein Problem von WooC 3.0
